openapi: 3.0.0 # need this as first line to allow IDEA to recognize it as op
info:
  title: Connector Meta Service
  version: 0.0.1
  description: Interface to the connector meta service
servers:
  - url: http://localhost:9091
    description: localhost
  - url: /
    description: current domain
paths:
  '/reify':
    post:
      requestBody:
        description: Connector deployment data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectorDeploymentReifyRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectorDeploymentSpec'
          description: The connector deployment spec
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No matching connector type exists
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      operationId: connectorDeploymentReifyRequest
      summary: Reify

components:
  schemas:

    ConnectorDeploymentReifyRequest:
      description: Holds the deployment specification of a connector to be reified
      type: object
      properties:
        managed_connector_id:
          type: string
        shard_metadata:
          type: object
        deployment_id:
          type: string
        deployment_resource_version:
          type: integer
          format: int64
        kafka_spec:
          $ref: '#/components/schemas/KafkaSpec'
        connector_id:
          type: string
        connector_type_id:
          type: string
        connector_spec:
          type: object
        connector_resource_version:
          type: integer
          format: int64
        desired_state:
          type: string
        allow_upgrade:
          type: boolean
        operator:
          $ref: '#/components/schemas/Operator'

    ConnectorDeploymentSpec:
      description: Holds the deployment specification of a connector
      type: object
      properties:
        resources:
          type: array
          items:
            type: object
        status_extractor:
          $ref: '#/components/schemas/StatusExtractor'

    KafkaSpec:
      properties:
        id:
          type: string
        bootstrap_server:
          type: string
        client_id:
          type: string
        client_secret:
          type: string

    StatusExtractor:
      description: Status eextractor.
      type: object
      properties:
        ref:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            name:
              type: string
        phase:
          type: object
          properties:
            path:
              type: string
              default: "/status/phase"
            mapping:
              type: array
              items:
                type: object
                properties:
                  resource:
                    type: string
                  connector:
                    type: string
        conditions:
          type: object
          properties:
            path:
              type: string
              default: "/status/conditions"
            types:
              type: array
              items:
                type: string

    Error:
      allOf:
        - $ref: "#/components/schemas/ObjectReference"
        - type: object
          properties:
            code:
              type: string
            reason:
              type: string
            operation_id:
              type: string

    ObjectReference:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string

    Operator:
      type: object
      properties:
        type:
          type: string
        version:
          type: string
      required:
        - type
        - version