apiVersion: cos.bf2.org/v1alpha1
kind: CamelConnector
metadata:
  annotations:
    cos.bf2.org/connector.id: c1
  name: camel-2
spec:
  connector:
    kamelets:
    - apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      spec:
        flow: 
          field: test
