---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: 260678543c5416d0ab256c721a7fe4ff0e9f775d
    app.quarkus.io/vcs-url: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard.git
    app.quarkus.io/build-timestamp: 2021-05-20 - 14:48:03 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator
    app.kubernetes.io/version: 999-SNAPSHOT
  name: cos-fleetshard-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: 260678543c5416d0ab256c721a7fe4ff0e9f775d
    app.quarkus.io/vcs-url: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard.git
    app.quarkus.io/build-timestamp: 2021-05-20 - 14:48:03 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator
    app.kubernetes.io/version: 999-SNAPSHOT
  name: cos-fleetshard-operator
spec:
  ports:
  - name: http
    port: 9095
    targetPort: 9095
  selector:
    app.kubernetes.io/name: cos-fleetshard-operator
    app.kubernetes.io/version: 999-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cos-fleetshard-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: cos-fleetshard-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cos-fleetshard-operator-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
- kind: ServiceAccount
  name: cos-fleetshard-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    app.quarkus.io/commit-id: 260678543c5416d0ab256c721a7fe4ff0e9f775d
    app.quarkus.io/vcs-url: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard.git
    app.quarkus.io/build-timestamp: 2021-05-20 - 14:48:03 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator
    app.kubernetes.io/version: 999-SNAPSHOT
  name: cos-fleetshard-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-operator
      app.kubernetes.io/version: 999-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        app.quarkus.io/commit-id: 260678543c5416d0ab256c721a7fe4ff0e9f775d
        app.quarkus.io/vcs-url: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard.git
        app.quarkus.io/build-timestamp: 2021-05-20 - 14:48:03 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
      labels:
        app.kubernetes.io/name: cos-fleetshard-operator
        app.kubernetes.io/version: 999-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/lburgazzoli/cfo:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: cos-fleetshard-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: cos-fleetshard-operator
